// Dữ liệu từ vựng (128 từ, đã đầy đủ)
const vocabularyData = [
  // 1. Đại từ & nhân xưng (9)
  { chinese: "你", pinyin: "nǐ", meaning: "bạn", category: "1" },
  { chinese: "你好", pinyin: "nǐ hǎo", meaning: "xin chào", category: "1" },
  { chinese: "我", pinyin: "wǒ", meaning: "tôi", category: "1" },
  { chinese: "他", pinyin: "tā", meaning: "anh ấy", category: "1" },
  { chinese: "她", pinyin: "tā", meaning: "cô ấy", category: "1" },
  { chinese: "们", pinyin: "men", meaning: "(hậu tố số nhiều)", category: "1" },
  { chinese: "谁", pinyin: "shéi", meaning: "ai", category: "1" },
  { chinese: "什么", pinyin: "shénme", meaning: "cái gì", category: "1" },
  { chinese: "您", pinyin: "nín", meaning: "ngài (kính ngữ)", category: "1" },

  // 2. Động từ & trợ động từ (21)
  { chinese: "叫", pinyin: "jiào", meaning: "gọi, tên là", category: "2" },
  { chinese: "是", pinyin: "shì", meaning: "là", category: "2" },
  { chinese: "说", pinyin: "shuō", meaning: "nói", category: "2" },
  { chinese: "会", pinyin: "huì", meaning: "biết, có thể", category: "2" },
  { chinese: "去", pinyin: "qù", meaning: "đi", category: "2" },
  { chinese: "回", pinyin: "huí", meaning: "về", category: "2" },
  { chinese: "学", pinyin: "xué", meaning: "học", category: "2" },
  { chinese: "写", pinyin: "xiě", meaning: "viết", category: "2" },
  { chinese: "吃", pinyin: "chī", meaning: "ăn", category: "2" },
  { chinese: "喝", pinyin: "hē", meaning: "uống", category: "2" },
  { chinese: "想", pinyin: "xiǎng", meaning: "muốn, nghĩ", category: "2" },
  { chinese: "买", pinyin: "mǎi", meaning: "mua", category: "2" },
  { chinese: "来", pinyin: "lái", meaning: "đến", category: "2" },
  { chinese: "做", pinyin: "zuò", meaning: "làm", category: "2" },
  { chinese: "要", pinyin: "yào", meaning: "muốn, cần", category: "2" },
  { chinese: "有", pinyin: "yǒu", meaning: "có", category: "2" },
  { chinese: "没有", pinyin: "méiyǒu", meaning: "không có", category: "2" },
  { chinese: "一起", pinyin: "yìqǐ", meaning: "cùng nhau", category: "2" },
  { chinese: "还要", pinyin: "hái yào", meaning: "còn phải, vẫn cần", category: "2" },
  { chinese: "看", pinyin: "kàn", meaning: "xem, nhìn", category: "2" },
  { chinese: "看见", pinyin: "kànjiàn", meaning: "nhìn thấy", category: "2" },

  // 3. Nghề nghiệp & quan hệ (9)
  { chinese: "学生", pinyin: "xuéshēng", meaning: "học sinh, sinh viên", category: "3" },
  { chinese: "工程师", pinyin: "gōngchéngshī", meaning: "kỹ sư", category: "3" },
  { chinese: "老师", pinyin: "lǎoshī", meaning: "giáo viên", category: "3" },
  { chinese: "朋友", pinyin: "péngyǒu", meaning: "bạn bè", category: "3" },
  { chinese: "同学", pinyin: "tóngxué", meaning: "bạn học", category: "3" },
  { chinese: "爸爸", pinyin: "bàba", meaning: "bố", category: "3" },
  { chinese: "妈妈", pinyin: "māma", meaning: "mẹ", category: "3" },
  { chinese: "弟弟", pinyin: "dìdi", meaning: "em trai", category: "3" },
  { chinese: "员工", pinyin: "yuángōng", meaning: "nhân viên", category: "3" },

  // 4. Quốc gia & dân tộc (4)
  { chinese: "中国", pinyin: "Zhōngguó", meaning: "Trung Quốc", category: "4" },
  { chinese: "美国", pinyin: "Měiguó", meaning: "Mỹ", category: "4" },
  { chinese: "越南", pinyin: "Yuènán", meaning: "Việt Nam", category: "4" },
  { chinese: "人", pinyin: "rén", meaning: "người", category: "4" },

  // 5. Ngôn ngữ & chữ viết (4)
  { chinese: "汉语", pinyin: "Hànyǔ", meaning: "tiếng Trung", category: "5" },
  { chinese: "英语", pinyin: "Yīngyǔ", meaning: "tiếng Anh", category: "5" },
  { chinese: "越南语", pinyin: "Yuènányǔ", meaning: "tiếng Việt", category: "5" },
  { chinese: "汉字", pinyin: "Hànzì", meaning: "chữ Hán", category: "5" },

  // 6. Thời gian & số đếm (26)
  { chinese: "今天", pinyin: "jīntiān", meaning: "hôm nay", category: "6" },
  { chinese: "昨天", pinyin: "zuótiān", meaning: "hôm qua", category: "6" },
  { chinese: "明天", pinyin: "míngtiān", meaning: "ngày mai", category: "6" },
  { chinese: "现在", pinyin: "xiànzài", meaning: "bây giờ", category: "6" },
  { chinese: "上午", pinyin: "shàngwǔ", meaning: "buổi sáng", category: "6" },
  { chinese: "中午", pinyin: "zhōngwǔ", meaning: "buổi trưa", category: "6" },
  { chinese: "下午", pinyin: "xiàwǔ", meaning: "buổi chiều", category: "6" },
  { chinese: "年", pinyin: "nián", meaning: "năm", category: "6" },
  { chinese: "月", pinyin: "yuè", meaning: "tháng", category: "6" },
  { chinese: "生日", pinyin: "shēngrì", meaning: "sinh nhật", category: "6" },
  { chinese: "点", pinyin: "diǎn", meaning: "giờ", category: "6" },
  { chinese: "分", pinyin: "fēn", meaning: "phút", category: "6" },
  { chinese: "一", pinyin: "yī", meaning: "một", category: "6" },
  { chinese: "二", pinyin: "èr", meaning: "hai", category: "6" },
  { chinese: "三", pinyin: "sān", meaning: "ba", category: "6" },
  { chinese: "四", pinyin: "sì", meaning: "bốn", category: "6" },
  { chinese: "五", pinyin: "wǔ", meaning: "năm", category: "6" },
  { chinese: "六", pinyin: "liù", meaning: "sáu", category: "6" },
  { chinese: "七", pinyin: "qī", meaning: "bảy", category: "6" },
  { chinese: "八", pinyin: "bā", meaning: "tám", category: "6" },
  { chinese: "九", pinyin: "jiǔ", meaning: "chín", category: "6" },
  { chinese: "十", pinyin: "shí", meaning: "mười", category: "6" },
  { chinese: "零", pinyin: "líng", meaning: "số không", category: "6" },
  { chinese: "几", pinyin: "jǐ", meaning: "mấy, bao nhiêu", category: "6" },
  { chinese: "号", pinyin: "hào", meaning: "ngày, số", category: "6" },
  { chinese: "岁", pinyin: "suì", meaning: "tuổi", category: "6" },

  // 7. Thức ăn & đồ uống (18)
  { chinese: "苹果", pinyin: "píngguǒ", meaning: "táo", category: "7" },
  { chinese: "西瓜", pinyin: "xīguā", meaning: "dưa hấu", category: "7" },
  { chinese: "芒果", pinyin: "mángguǒ", meaning: "xoài", category: "7" },
  { chinese: "菠萝", pinyin: "bōluó", meaning: "dứa", category: "7" },
  { chinese: "鸡蛋", pinyin: "jīdàn", meaning: "trứng gà", category: "7" },
  { chinese: "面包", pinyin: "miànbāo", meaning: "bánh mì", category: "7" },
  { chinese: "饼干", pinyin: "bǐnggān", meaning: "bánh quy", category: "7" },
  { chinese: "水果", pinyin: "shuǐguǒ", meaning: "trái cây", category: "7" },
  { chinese: "茶", pinyin: "chá", meaning: "trà", category: "7" },
  { chinese: "咖啡", pinyin: "kāfēi", meaning: "cà phê", category: "7" },
  { chinese: "果汁", pinyin: "guǒzhī", meaning: "nước ép", category: "7" },
  { chinese: "水", pinyin: "shuǐ", meaning: "nước", category: "7" },
  { chinese: "牛奶", pinyin: "niúnǎi", meaning: "sữa", category: "7" },
  { chinese: "啤酒", pinyin: "píjiǔ", meaning: "bia", category: "7" },
  { chinese: "可乐", pinyin: "kělè", meaning: "coca", category: "7" },
  { chinese: "饭", pinyin: "fàn", meaning: "cơm, bữa ăn", category: "7" },
  { chinese: "杯", pinyin: "bēi", meaning: "cốc, ly (lượng)", category: "7" },
  { chinese: "杯子", pinyin: "bēizi", meaning: "cái cốc, cái ly", category: "7" },

  // 8. Mua sắm & tiền bạc (3)
  { chinese: "钱", pinyin: "qián", meaning: "tiền", category: "8" },
  { chinese: "块", pinyin: "kuài", meaning: "đồng (khẩu ngữ)", category: "8" },
  { chinese: "多少", pinyin: "duōshao", meaning: "bao nhiêu", category: "8" },

  // 9. Đồ vật & địa điểm (5)
  { chinese: "家", pinyin: "jiā", meaning: "nhà", category: "9" },
  { chinese: "学校", pinyin: "xuéxiào", meaning: "trường học", category: "9" },
  { chinese: "上", pinyin: "shàng", meaning: "trên", category: "9" },
  { chinese: "桌子", pinyin: "zhuōzi", meaning: "cái bàn", category: "9" },
  { chinese: "椅子", pinyin: "yǐzi", meaning: "cái ghế", category: "9" },

  // 10. Từ khác (29)
  { chinese: "名字", pinyin: "míngzi", meaning: "tên", category: "10" },
  { chinese: "不", pinyin: "bù", meaning: "không", category: "10" },
  { chinese: "都", pinyin: "dōu", meaning: "đều", category: "10" },
  { chinese: "也", pinyin: "yě", meaning: "cũng", category: "10" },
  { chinese: "和", pinyin: "hé", meaning: "và", category: "10" },
  { chinese: "喜欢", pinyin: "xǐhuān", meaning: "thích", category: "10" },
  { chinese: "再见", pinyin: "zàijiàn", meaning: "tạm biệt", category: "10" },
  { chinese: "吗", pinyin: "ma", meaning: "trợ từ nghi vấn", category: "10" },
  { chinese: "哪", pinyin: "nǎ", meaning: "nào", category: "10" },
  { chinese: "这", pinyin: "zhè", meaning: "cái này, đây", category: "10" },
  { chinese: "那", pinyin: "nà", meaning: "kia, cái kia", category: "10" },
  { chinese: "大", pinyin: "dà", meaning: "to, lớn", category: "10" },
  { chinese: "小", pinyin: "xiǎo", meaning: "nhỏ", category: "10" },
  { chinese: "呢", pinyin: "ne", meaning: "trợ từ (thì sao)", category: "10" },
  { chinese: "对不起", pinyin: "duìbuqǐ", meaning: "xin lỗi", category: "10" },
  { chinese: "没关系", pinyin: "méiguānxi", meaning: "không sao", category: "10" },
  { chinese: "谢谢", pinyin: "xièxie", meaning: "cảm ơn", category: "10" },
  { chinese: "不客气", pinyin: "bú kèqi", meaning: "không có gì", category: "10" },
  { chinese: "个", pinyin: "gè", meaning: "lượng từ chung", category: "10" },
  { chinese: "了", pinyin: "le", meaning: "trợ từ (thay đổi/hoàn thành)", category: "10" },
  { chinese: "在", pinyin: "zài", meaning: "ở, tại", category: "10" },
  { chinese: "晚上好", pinyin: "wǎnshang hǎo", meaning: "chào buổi tối", category: "10" },
  { chinese: "好的", pinyin: "hǎo de", meaning: "được, ok", category: "10" },
  { chinese: "辛苦了", pinyin: "xīnkǔ le", meaning: "vất vả rồi", category: "10" },
  { chinese: "一点儿", pinyin: "yīdiǎnr", meaning: "một chút, một ít", category: "10" },
  { chinese: "里", pinyin: "lǐ", meaning: "trong, bên trong", category: "10" },
  { chinese: "还", pinyin: "hái", meaning: "còn, vẫn", category: "10" },
  { chinese: "再", pinyin: "zài", meaning: "lại, nữa", category: "10" },
  { chinese: "跟", pinyin: "gēn", meaning: "với, cùng", category: "10" },
  { chinese: "非常", pinyin: "fēicháng", meaning: "rất, vô cùng", category: "10" }
];

// Tên danh mục
const categoryNames = {
  "1": "Đại từ & nhân xưng",
  "2": "Động từ & trợ động từ",
  "3": "Nghề nghiệp & quan hệ",
  "4": "Quốc gia & dân tộc",
  "5": "Ngôn ngữ & chữ viết",
  "6": "Thời gian & số đếm",
  "7": "Thức ăn & đồ uống",
  "8": "Mua sắm & tiền bạc",
  "9": "Đồ vật & địa điểm",
  "10": "Từ khác"
};
