// Dữ liệu từ vựng
const vocabularyData = [
  // 1. Đại từ & nhân xưng (7)
  { chinese: "你", pinyin: "nǐ", meaning: "bạn", category: "1" },
  { chinese: "我", pinyin: "wǒ", meaning: "tôi", category: "1" },
  { chinese: "她", pinyin: "tā", meaning: "cô ấy, bà ấy", category: "1" },
  { chinese: "他", pinyin: "tā", meaning: "anh ấy, ông ấy", category: "1" },
  { chinese: "我们", pinyin: "wǒmen", meaning: "chúng tôi, chúng ta", category: "1" },
  { chinese: "您", pinyin: "nín", meaning: "ngài, ông, bà (kính ngữ)", category: "1" },
  { chinese: "们", pinyin: "men", meaning: "các (hậu tố số nhiều)", category: "1" },

  // 2. Động từ & trợ động từ (22)
  { chinese: "是", pinyin: "shì", meaning: "là", category: "2" },
  { chinese: "叫", pinyin: "jiào", meaning: "tên là, gọi là", category: "2" },
  { chinese: "不", pinyin: "bù", meaning: "không", category: "2" },
  { chinese: "说", pinyin: "shuō", meaning: "nói", category: "2" },
  { chinese: "会", pinyin: "huì", meaning: "biết, có thể", category: "2" },
  { chinese: "学", pinyin: "xué", meaning: "học", category: "2" },
  { chinese: "写", pinyin: "xiě", meaning: "viết", category: "2" },
  { chinese: "吃", pinyin: "chī", meaning: "ăn", category: "2" },
  { chinese: "喜欢", pinyin: "xǐhuan", meaning: "thích", category: "2" },
  { chinese: "喝", pinyin: "hē", meaning: "uống", category: "2" },
  { chinese: "想", pinyin: "xiǎng", meaning: "muốn, nghĩ", category: "2" },
  { chinese: "买", pinyin: "mǎi", meaning: "mua", category: "2" },
  { chinese: "有", pinyin: "yǒu", meaning: "có", category: "2" },
  { chinese: "没有", pinyin: "méiyǒu", meaning: "không có", category: "2" },
  { chinese: "做", pinyin: "zuò", meaning: "làm", category: "2" },
  { chinese: "去", pinyin: "qù", meaning: "đi", category: "2" },
  { chinese: "回", pinyin: "huí", meaning: "về, quay lại", category: "2" },
  { chinese: "来", pinyin: "lái", meaning: "đến", category: "2" },
  { chinese: "看", pinyin: "kàn", meaning: "nhìn, xem", category: "2" },
  { chinese: "看见", pinyin: "kànjiàn", meaning: "nhìn thấy", category: "2" },
  { chinese: "要", pinyin: "yào", meaning: "cần, muốn", category: "2" },
  { chinese: "没", pinyin: "méi", meaning: "không (viết tắt)", category: "2" },

  // 3. Nghề nghiệp & quan hệ (15)
  { chinese: "学生", pinyin: "xuésheng", meaning: "học sinh", category: "3" },
  { chinese: "工程师", pinyin: "gōngchéngshī", meaning: "kỹ sư", category: "3" },
  { chinese: "老师", pinyin: "lǎoshī", meaning: "thầy giáo, cô giáo", category: "3" },
  { chinese: "爸爸", pinyin: "bàba", meaning: "bố, ba", category: "3" },
  { chinese: "妈妈", pinyin: "māma", meaning: "mẹ", category: "3" },
  { chinese: "弟弟", pinyin: "dìdi", meaning: "em trai", category: "3" },
  { chinese: "朋友", pinyin: "péngyǒu", meaning: "bạn bè", category: "3" },
  { chinese: "同学", pinyin: "tóngxué", meaning: "bạn học", category: "3" },
  { chinese: "人", pinyin: "rén", meaning: "người", category: "3" },
  { chinese: "员工", pinyin: "yuángōng", meaning: "nhân viên", category: "3" },
  { chinese: "职员", pinyin: "zhíyuán", meaning: "nhân viên văn phòng", category: "3" },
  { chinese: "先生", pinyin: "xiānsheng", meaning: "ông, ngài", category: "3" },
  { chinese: "妻子", pinyin: "qīzi", meaning: "vợ", category: "3" },
  { chinese: "女儿", pinyin: "nǚ'ér", meaning: "con gái", category: "3" },
  { chinese: "儿子", pinyin: "érzi", meaning: "con trai", category: "3" },

  // 4. Quốc gia & dân tộc (3)
  { chinese: "中国", pinyin: "zhōngguó", meaning: "Trung Quốc", category: "4" },
  { chinese: "美国", pinyin: "měiguó", meaning: "Mỹ", category: "4" },
  { chinese: "越南", pinyin: "yuènán", meaning: "Việt Nam", category: "4" },

  // 5. Ngôn ngữ & chữ viết (4)
  { chinese: "汉语", pinyin: "hànyǔ", meaning: "tiếng Hán, tiếng Trung", category: "5" },
  { chinese: "英语", pinyin: "yīngyǔ", meaning: "tiếng Anh", category: "5" },
  { chinese: "越南语", pinyin: "yuènányǔ", meaning: "tiếng Việt", category: "5" },
  { chinese: "汉字", pinyin: "hànzì", meaning: "chữ Hán", category: "5" },

  // 6. Thời gian & số đếm (25)
  { chinese: "一", pinyin: "yī", meaning: "một", category: "6" },
  { chinese: "二", pinyin: "èr", meaning: "hai", category: "6" },
  { chinese: "三", pinyin: "sān", meaning: "ba", category: "6" },
  { chinese: "四", pinyin: "sì", meaning: "bốn", category: "6" },
  { chinese: "五", pinyin: "wǔ", meaning: "năm", category: "6" },
  { chinese: "六", pinyin: "liù", meaning: "sáu", category: "6" },
  { chinese: "七", pinyin: "qī", meaning: "bảy", category: "6" },
  { chinese: "八", pinyin: "bā", meaning: "tám", category: "6" },
  { chinese: "九", pinyin: "jiǔ", meaning: "chín", category: "6" },
  { chinese: "十", pinyin: "shí", meaning: "mười", category: "6" },
  { chinese: "零", pinyin: "líng", meaning: "không (số 0)", category: "6" },
  { chinese: "百", pinyin: "bǎi", meaning: "trăm", category: "6" },
  { chinese: "今天", pinyin: "jīntiān", meaning: "hôm nay", category: "6" },
  { chinese: "昨天", pinyin: "zuótiān", meaning: "hôm qua", category: "6" },
  { chinese: "明天", pinyin: "míngtiān", meaning: "ngày mai", category: "6" },
  { chinese: "上午", pinyin: "shàngwǔ", meaning: "buổi sáng", category: "6" },
  { chinese: "中午", pinyin: "zhōngwǔ", meaning: "buổi trưa", category: "6" },
  { chinese: "下午", pinyin: "xiàwǔ", meaning: "buổi chiều", category: "6" },
  { chinese: "月", pinyin: "yuè", meaning: "tháng", category: "6" },
  { chinese: "年", pinyin: "nián", meaning: "năm", category: "6" },
  { chinese: "岁", pinyin: "suì", meaning: "tuổi", category: "6" },
  { chinese: "生日", pinyin: "shēngrì", meaning: "sinh nhật", category: "6" },
  { chinese: "现在", pinyin: "xiànzài", meaning: "bây giờ", category: "6" },
  { chinese: "点", pinyin: "diǎn", meaning: "giờ", category: "6" },
  { chinese: "分", pinyin: "fēn", meaning: "phút", category: "6" },

  // 7. Thức ăn & đồ uống (17)
  { chinese: "饭", pinyin: "fàn", meaning: "cơm", category: "7" },
  { chinese: "水果", pinyin: "shuǐguǒ", meaning: "trái cây", category: "7" },
  { chinese: "苹果", pinyin: "píngguǒ", meaning: "quả táo", category: "7" },
  { chinese: "西瓜", pinyin: "xīguā", meaning: "dưa hấu", category: "7" },
  { chinese: "芒果", pinyin: "mángguǒ", meaning: "xoài", category: "7" },
  { chinese: "菠萝", pinyin: "bōluó", meaning: "dứa", category: "7" },
  { chinese: "鸡蛋", pinyin: "jīdàn", meaning: "trứng gà", category: "7" },
  { chinese: "面包", pinyin: "miànbāo", meaning: "bánh mì", category: "7" },
  { chinese: "饼干", pinyin: "bǐnggān", meaning: "bánh quy", category: "7" },
  { chinese: "茶", pinyin: "chá", meaning: "trà", category: "7" },
  { chinese: "咖啡", pinyin: "kāfēi", meaning: "cà phê", category: "7" },
  { chinese: "果汁", pinyin: "guǒzhī", meaning: "nước ép trái cây", category: "7" },
  { chinese: "水", pinyin: "shuǐ", meaning: "nước", category: "7" },
  { chinese: "牛奶", pinyin: "niúnǎi", meaning: "sữa bò", category: "7" },
  { chinese: "啤酒", pinyin: "píjiǔ", meaning: "bia", category: "7" },
  { chinese: "可乐", pinyin: "kělè", meaning: "coca", category: "7" },
  { chinese: "蛋糕", pinyin: "dàngāo", meaning: "bánh gato", category: "7" },

  // 8. Mua sắm & tiền bạc (4)
  { chinese: "钱", pinyin: "qián", meaning: "tiền", category: "8" },
  { chinese: "块", pinyin: "kuài", meaning: "đồng (đơn vị tiền)", category: "8" },
  { chinese: "买", pinyin: "mǎi", meaning: "mua", category: "8" },
  { chinese: "多少", pinyin: "duōshao", meaning: "bao nhiêu", category: "8" },

  // 9. Đồ vật & địa điểm (9)
  { chinese: "家", pinyin: "jiā", meaning: "nhà, gia đình", category: "9" },
  { chinese: "学校", pinyin: "xuéxiào", meaning: "trường học", category: "9" },
  { chinese: "桌子", pinyin: "zhuōzi", meaning: "cái bàn", category: "9" },
  { chinese: "椅子", pinyin: "yǐzi", meaning: "cái ghế", category: "9" },
  { chinese: "杯子", pinyin: "bēizi", meaning: "cái cốc", category: "9" },
  { chinese: "杯", pinyin: "bēi", meaning: "cốc, chén", category: "9" },
  { chinese: "饭店", pinyin: "fàndiàn", meaning: "nhà hàng, khách sạn", category: "9" },
  { chinese: "商店", pinyin: "shāngdiàn", meaning: "cửa hàng, tiệm", category: "9" },
  { chinese: "前面", pinyin: "qiánmiàn", meaning: "phía trước", category: "9" },

  // 10. Từ khác (41)
  { chinese: "好", pinyin: "hǎo", meaning: "tốt, khỏe", category: "10" },
  { chinese: "名字", pinyin: "míngzi", meaning: "tên", category: "10" },
  { chinese: "哪", pinyin: "nǎ", meaning: "nào, ở đâu", category: "10" },
  { chinese: "谁", pinyin: "shéi", meaning: "ai", category: "10" },
  { chinese: "再见", pinyin: "zàijiàn", meaning: "tạm biệt", category: "10" },
  { chinese: "吗", pinyin: "ma", meaning: "không? (trợ từ nghi vấn)", category: "10" },
  { chinese: "都", pinyin: "dōu", meaning: "đều, tất cả", category: "10" },
  { chinese: "里", pinyin: "lǐ", meaning: "trong, ở trong", category: "10" },
  { chinese: "也", pinyin: "yě", meaning: "cũng", category: "10" },
  { chinese: "和", pinyin: "hé", meaning: "và", category: "10" },
  { chinese: "这", pinyin: "zhè", meaning: "đây, cái này", category: "10" },
  { chinese: "那", pinyin: "nà", meaning: "kia, cái kia", category: "10" },
  { chinese: "大", pinyin: "dà", meaning: "to, lớn", category: "10" },
  { chinese: "小", pinyin: "xiǎo", meaning: "nhỏ", category: "10" },
  { chinese: "什么", pinyin: "shénme", meaning: "gì, cái gì", category: "10" },
  { chinese: "几", pinyin: "jǐ", meaning: "mấy", category: "10" },
  { chinese: "呢", pinyin: "ne", meaning: "nhỉ, nhé (trợ từ)", category: "10" },
  { chinese: "对不起", pinyin: "duìbùqǐ", meaning: "xin lỗi", category: "10" },
  { chinese: "没关系", pinyin: "méiguānxi", meaning: "không sao", category: "10" },
  { chinese: "谢谢", pinyin: "xièxie", meaning: "cảm ơn", category: "10" },
  { chinese: "不客气", pinyin: "búkèqi", meaning: "không có gì, đừng khách sáo", category: "10" },
  { chinese: "个", pinyin: "ge", meaning: "cái, chiếc (lượng từ)", category: "10" },
  { chinese: "号", pinyin: "hào", meaning: "số, ngày", category: "10" },
  { chinese: "了", pinyin: "le", meaning: "rồi (trợ từ)", category: "10" },
  { chinese: "在", pinyin: "zài", meaning: "ở, đang", category: "10" },
  { chinese: "晚上好", pinyin: "wǎnshàng hǎo", meaning: "chào buổi tối", category: "10" },
  { chinese: "好的", pinyin: "hǎode", meaning: "được, vâng (đồng ý)", category: "10" },
  { chinese: "辛苦了", pinyin: "xīnkǔle", meaning: "vất vả rồi", category: "10" },
  { chinese: "一点儿", pinyin: "yìdiǎnr", meaning: "một chút", category: "10" },
  { chinese: "上", pinyin: "shàng", meaning: "trên", category: "10" },
  { chinese: "很", pinyin: "hěn", meaning: "rất", category: "10" },
  { chinese: "猫", pinyin: "māo", meaning: "mèo", category: "10" },
  { chinese: "狗", pinyin: "gǒu", meaning: "chó", category: "10" },
  { chinese: "下", pinyin: "xià", meaning: "dưới, xuống", category: "10" },
  { chinese: "漂亮", pinyin: "piàoliang", meaning: "đẹp", category: "10" },
  { chinese: "多", pinyin: "duō", meaning: "nhiều", category: "10" },
  { chinese: "高兴", pinyin: "gāoxìng", meaning: "vui vẻ, vui mừng", category: "10" },
  { chinese: "东西", pinyin: "dōngxi", meaning: "đồ vật, thứ", category: "10" },
  { chinese: "衣服", pinyin: "yīfu", meaning: "quần áo", category: "10" },
  { chinese: "哪儿", pinyin: "nǎr", meaning: "ở đâu", category: "10" },
  { chinese: "些", pinyin: "xiē", meaning: "một vài, một số", category: "10" },
];

// Tên danh mục
const categoryNames = {
  "1": "Đại từ & nhân xưng",
  "2": "Động từ & trợ động từ",
  "3": "Nghề nghiệp & quan hệ",
  "4": "Quốc gia & dân tộc",
  "5": "Ngôn ngữ & chữ viết",
  "6": "Thời gian & số đếm",
  "7": "Thức ăn & đồ uống",
  "8": "Mua sắm & tiền bạc",
  "9": "Đồ vật & địa điểm",
  "10": "Từ khác"
};




